plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}
apply from: "../common.gradle"
android {
    namespace 'com.cv.pic.exo.video'
}

dependencies {
  implementation "androidx.media3:media3-exoplayer:1.7.1"
  implementation "androidx.media3:media3-exoplayer-dash:1.7.1"
  implementation "androidx.media3:media3-exoplayer-hls:1.7.1"
  implementation "androidx.media3:media3-exoplayer-rtsp:1.7.1"
  implementation "androidx.media3:media3-ui:1.7.1"
  implementation "androidx.media3:media3-session:1.7.1"
  implementation "androidx.media3:media3-datasource-okhttp:1.7.1"
  implementation "androidx.media3:media3-datasource-cronet:1.7.1"

  // 加密支持
  implementation 'androidx.media3:media3-decoder:1.7.1'
  implementation 'androidx.media3:media3-common:1.7.1'

  // 文件操作
  implementation 'commons-io:commons-io:2.19.0'

  implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
}