plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}
apply from: "../common.gradle"
android {
    namespace 'com.cv.pic.db'
}

dependencies {
  implementation "androidx.room:room-runtime:2.7.2"
  kapt "androidx.room:room-compiler:2.7.2"
  implementation "androidx.room:room-ktx:2.7.2" // Kotlin扩展和协程支持
//
//  // 可选：SQLite调试工具
//  debugImplementation 'com.guolindev.glance:glance:1.1.0'
//
//  // 数据库加密
  implementation "net.zetetic:android-database-sqlcipher:4.5.4"

}